#!/bin/bash 
# author: Leon van Kammen / Coder of Salvation 2014
# 
# simple consolewrapper for notmuch to save yourself from typing all the time

C_NORMAL="\\033[0;0m"
C_GREEN="\\033[0;32m"
cache=()

# here you can define your preset calls
# the variables can be insert directly in the console ('foo=flop' e.g.)
cache+=('search tag:todo')
cache+=('search tag:unread')
cache+=('showtags')
notmuch search --output=tags '*' > ~/.notmuch.tags
while read line; do cache+=("search tag:$line"); done < ~/.notmuch.tags
cache+=('search tag:inbox')

ITEMS=()
tags=""

# utility functions
function wraplines(){
    cat - | cut -c 1-$(tput cols)
}

function columnize(){
  cat - | while read line; do 
    prefix="${line/;*/}"; prefix="${prefix/\[*\]/}"
    suffix="${line/*;/}"
    printf "%-70s   %-70s\n" "${prefix:0:70}" "$suffix"  
  done
}

# lets teach some history 
teach(){
  for line in "${cache[@]}"; do
    history -s -- "$line"
  done
}

# text formatting routines
filter(){
  printf "$C_NORMAL"
  case "$1" in
    show*)      cat - | grep -vE "(message{|header{|header}|body{|body}|part{|part}|message}|message{)"
                ;;
    *)          cat - | wraplines
                ;;
  esac 
  printf "$C_NORMAL"
}

aliases(){
  arg="$1";
  arg="${arg/search /search --sort=newest-first }"
  arg="${arg/tags/search --output=tags '*'}"
  echo "$arg"
}

process(){
  arg="$(aliases "$1")"
  [[ "$arg" =~ ^search" " ]] || [[ "$arg" =~ ^show" " ]] || [[ "$arg" =~ ^searchshow" " ]] || [[ "$arg" =~ ^tag" " ]] && {
    eval "notmuch ${arg} | filter \"$arg\" | more" 
    return 0;
  }
  [[ "$arg" == "exit" ]] || [[ "$arg" == "quit" ]] && exit 0
  eval "$line"
  teach
}

showtags(){
  printf "\n$C_WHITE""possible tags:\n$C_GREEN"
  echo "$tags" | pr -o2 -T --columns=5
  printf "$C_NORMAL"
}

subconsole(){
  printf "$tags"
  echo -e "type 'exit' to quit\n"
  while IFS="" read -r -e -d $'\n' -p "$2> " line; do
    printf "$C_WHITE"
    "$1" "$line"
    printf "$C_GREEN"
    #history -s "$line" # lets not add performed command to history
  done
}

echo -e "\npress arrow up to cycle suggestions"
teach; [[ ! -n "$1" ]] && subconsole process "notmuchbash" || process "$*"
